name: MLwC
channels:
- conda-forge
- defaults
- anaconda
dependencies:
- python>=3.8
- jupyter
- jupyterlab>=3.0
- pip
- matplotlib
- numpy
- tensorflow
- tqdm
- missingno
- pyjanitor
- black
- nbstripout
- pylint
- ipykernel
- hvplot
- bokeh
- holoviews
- mkl
- mkl-service
- pre-commit
- mamba  #fast conda env solver
- pyprojroot
- faker
- python-graphviz
- watermark
- pip:
  - mkdocs
  - mkdocs-material
  - mknotebooks
  - daft
  # Need to add pip install from github for repo, so solutions can be executed.
